/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-09-27
The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <time.h>
#include "stm32l1xx.h"


/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
void Delay(__IO uint32_t time);

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{

  uint8_t BUTTON = 0;
  uint8_t push_count = 0,push_count2 = 0, condition_count = 3;


  GPIO_InitTypeDef gpioInitStr;
  GPIO_InitTypeDef gpioaInitStr;

  RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOC,ENABLE);
  gpioInitStr.GPIO_Mode = GPIO_Mode_IN;
  gpioInitStr.GPIO_OType = GPIO_OType_PP;
  gpioInitStr.GPIO_PuPd = GPIO_PuPd_NOPULL;
  GPIO_Init(GPIOC,&gpioInitStr);

  RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA,ENABLE);
  gpioaInitStr.GPIO_Pin = GPIO_Pin_5;
  gpioaInitStr.GPIO_Mode = GPIO_Mode_OUT;
  gpioaInitStr.GPIO_OType = GPIO_OType_PP;
  gpioaInitStr.GPIO_PuPd = GPIO_PuPd_UP;
  gpioaInitStr.GPIO_Speed = GPIO_Speed_40MHz;
  GPIO_Init(GPIOA,&gpioaInitStr);



/*
  //RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA,ENABLE);
  //GPIO nastavime na vystup
  GPIOA->MODER|=(uint32_t)0b01<<(5*2);

  //GPIO nastavime na PushPull
  GPIOA->OTYPER&=~(uint32_t)0b1<<5;

  //GPIO nastavime na PullUp
  GPIOA->PUPDR&=~(uint32_t)0b1<<(5*2+1);
  GPIOA->PUPDR|=(uint32_t)0b1<<(5*2);

  //GPIO nastavime na HighSpeed
  GPIOA->OSPEEDR|=(uint32_t)0b1<<(5*2+1);
  GPIOA->OSPEEDR&=~(uint32_t)0b1<<(5*2);
*/



  /**
  *  IMPORTANT NOTE!
  *  See the <system_*.c> file and how/if the SystemInit() function updates 
  *  SCB->VTOR register. Sometimes the symbol VECT_TAB_SRAM needs to be defined 
  *  when building the project if code has been located to RAM and interrupts 
  *  are used. Otherwise the interrupt table located in flash will be used.
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /**
  *  At this stage the microcontroller clock setting is already configured,
  *  this is done through SystemInit() function which is called from startup
  *  file (startup_stm32l1xx_hd.s) before to branch to application main.
  *  To reconfigure the default setting of SystemInit() function, refer to
  *  system_stm32l1xx.c file
  */

  /* TODO - Add your application code here */


  /* Infinite loop */
  while (1)
  {
	   // zapnutie LED pomocou registra ODR
	   //GPIOA->ODR|=(uint32_t)0b1<<5;
	  //GPIO_SetBits(GPIOA, GPIO_Pin_5);
	   // vypnutie LED pomocou registra ODR
	   //GPIOA->ODR&=~(uint32_t)0b1<<5;
	  //GPIO_ResetBits(GPIOA, GPIO_Pin_5);
	  //nastavime bit pomocou registra BSRR
	  //GPIOA->BSRRL|=(uint16_t)0b01<<(5);
	  //GPIOA->BSRRH|=(uint16_t)0b01<<(5);
	  //Prepínanie stavu LED pomocou ODR
	  //GPIOA->ODR^=(uint32_t)0b1<<5;

	  /*
	  for (int i = 0;i<condition_count;i++){
		  	  //ak je stlacene tlacidlo PC13
	  		  if ((GPIOC->IDR & ((uint32_t)(1<<13))) == 0){
	  			  push_count++;
	  			  if (push_count>condition_count){
	  			  BUTTON = 1;
	  			  }
	  		  }
	  		  else
	  			  BUTTON = 0;
	  	  }
		*/
	  /*
	  //blikanie LED pomocou casovaca resp. for cyklu
	  GPIOA->ODR^=(uint32_t)0b1<<5;
	  for(int i = 0; i < 500000; i++);
	 */
	  for (int i = 0;i<condition_count;i++){
	  	 		  	  //ak je stlacene tlacidlo PC13
	  	 	  		  //if ((GPIOC->IDR & ((uint32_t)(1<<13))) == 0){
		  	  	  	  if (GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13) == 0) {
	  	 	  			  push_count++;
	  	 	  			  if (push_count>condition_count){
	  	 	  				BUTTON = 1;
	  	 	  				push_count = 0;
	  	 	  			  }
	  	 	  		  }
	  	 	  		  if (BUTTON == 1){
	  	 	  			  if (GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13) != 0){
	  	 	  				  push_count2++;
	  	 	  				  if (push_count2>condition_count){
	  	 	  					  //GPIOA->ODR^=(uint32_t)0b1<<5;
	  	 	  					  GPIO_ToggleBits(GPIOA, GPIO_Pin_5);
	  	 	  					  BUTTON = 0;
	  	 	  					  push_count2 = 0;
	  	 	  				  }
	  	 	  			  }
	  	 	  		  }

	  	  }


  }
  return 0;
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
